// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantCityDiscordBot.Resources.Database;

namespace RestaurantCityDiscordBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20181004011713_invite_link")]
    partial class invite_link
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RestaurantCityDiscordBot.Resources.Database.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Have");

                    b.Property<string>("Need");

                    b.Property<ulong>("UserId");

                    b.Property<string>("inGameName");

                    b.Property<string>("inviteLink");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
